language: php

# Sudo: false should make the builds faster, but collides with rabbitmq
sudo: true

dist: trusty

matrix:
  include:
  # Test only on versions of Sf that are still supported. See: http://symfony.com/doc/current/contributing/community/releases.html#version-history
    - php: 5.4
      env: SYMFONY_VERSION=2.6.* CODE_COVERAGE=0 BROKER=apollo
    - php: 5.5
      env: SYMFONY_VERSION=2.7.* CODE_COVERAGE=0 BROKER=apollo
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* CODE_COVERAGE=1 BROKER=apollo
    - php: 7.0
      env: SYMFONY_VERSION=3.0.* CODE_COVERAGE=0 BROKER=apollo
    - php: hhvm
      env: SYMFONY_VERSION=3.1.* CODE_COVERAGE=0 BROKER=apollo
    - php: 5.4
      env: SYMFONY_VERSION=2.6.* CODE_COVERAGE=0 BROKER=activemq
    - php: 5.5
      env: SYMFONY_VERSION=2.7.* CODE_COVERAGE=0 BROKER=activemq
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* CODE_COVERAGE=0 BROKER=activemq
    - php: 7.0
      env: SYMFONY_VERSION=3.0.* CODE_COVERAGE=0 BROKER=activemq
    - php: hhvm
      env: SYMFONY_VERSION=3.1.* CODE_COVERAGE=0 BROKER=activemq

  #allow_failures:
    # The tests fail with activemq 5.5, which is the version currently available on Ubuntu 12. And there is no activemq in Ubuntu backports
    #- env: SYMFONY_VERSION=2.6.* BROKER=activemq

services:
  - rabbitmq

before_install:
  # This is mandatory or 'apt-get install' calls following will fail
  - sudo apt-get update -qq
  # Install a more recent Xdebug version, as the default one (2.2.7) crashes when generating code coverage
  #- if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then ./Tests/travis/setup_xdebug.sh; fi
  - ./Tests/travis/setup_broker.sh $BROKER

install:
  - phpenv config-add Tests/travis/zzz_php.ini

  # Disable xdebug for speed (executing composer), but allow us to re-enable it later
  # NB: 'php -i' does not work on hhvm
  - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then export XDEBUG_INI=''; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then export XDEBUG_INI=`php -i | grep xdebug.ini | grep home/travis | grep -v '=>' | head -1`; fi
  - export XDEBUG_INI=${XDEBUG_INI/,/}
  - if [ "$XDEBUG_INI" != "" ]; then mv "$XDEBUG_INI" "$XDEBUG_INI.bak"; fi

  - composer self-update
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}
  - composer install

  # Re-enable xdebug for when we need to generate code coverage
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a "$XDEBUG_INI" != "" ]; then mv "$XDEBUG_INI.bak" "$XDEBUG_INI"; fi

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then phpunit --colors --coverage-clover=coverage.clover Tests/phpunit; else phpunit --colors Tests/phpunit; fi

after_failure:
  # Display as much info as we can to help developers
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php -i; fi

after_script:
  # Upload code-coverage to Scrutinizer
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  # Upload code-coverage to CodeClimate
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" -a -f coverage.clover ]; then CODECLIMATE_REPO_TOKEN=TOBEGOTTEN ./vendor/bin/test-reporter --coverage-report=coverage.clover; fi

cache:
  directories:
    - $COMPOSER_CACHE_DIR
